version: "2"
linters-settings:
  errcheck:
    exclude: fmt:.*,io/ioutil:^Read.*,os\\.Setenv,.*\\.Close,.*\\.Flush
    exclude-tests: true

  gocritic:
    disabled-checks:
      - exitAfterDefer

  forbidigo:
    # Forbid the following identifiers
    forbid:
      - ^fmt\.Errorf$ # consider errors.Errorf in github.com/pkg/errors

linters:
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - exhaustive
    - bidichk
    - gocritic
    - goprintffuncname
    - govet
    - ineffassign
    - nolintlint
    - rowserrcheck
    - staticcheck
    - unused
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - revive
    - forbidigo
    - makezero

run:
  deadline: 5m
  issues-exit-code: 1
  skip-dirs: []
  tests: true

output:
  format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

issues:
  fix: true
  exclude-use-default: false
  exclude:
    - "Error return value of .((os.)?std(out|err)..*|.*Close|.*Seek|.*Flush|os.Remove(All)?|.*print(f|ln)?|os.(Un)?Setenv). is not check"
    - "Error return value of `os.Setenv` is not checked"
    - "Error return value of `rd.Close` is not checked"
    - "Error return value of `resp.Body.Close` is not checked"
    - "Error return value of `res.Body.Close` is not checked"
    - "Error return value of `file.Close` is not checked"
    - "Error return value of `writer.Flush` is not checked"
